// src/models/Notification.js – Persistent user notifications (deterministic, dedupe-safe)
const mongoose = require('mongoose');

const notificationSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    type: {
      type: String,
      required: true,
      trim: true,
      index: true,
    },
    title: { type: String, required: true, trim: true, maxlength: 140 },
    message: { type: String, required: true, trim: true, maxlength: 500 },
    description: { type: String, default: '', maxlength: 1000 },
    category: {
      type: String,
      enum: ['daily', 'onboarding', 'event', 'system', 'reminder', 'milestone'],
      default: 'daily',
      index: true,
    },
    priority: {
      type: String,
      enum: ['low', 'normal', 'high'],
      default: 'normal',
    },
    isRead: { type: Boolean, default: false, index: true },
    isBookmarked: { type: Boolean, default: false },
    scheduledAt: { type: Date, required: true },
    deliveredAt: { type: Date, default: () => new Date() },
    expiresAt: { type: Date, default: null },
    metadata: { type: mongoose.Schema.Types.Mixed, default: {} },
    action: {
      type: String,
      default: null,
    },
    // Deterministic key used for deduplication. Generated by notificationEngine.
    notificationKey: {
      type: String,
      default: null,
      index: true,
    },
  },
  { timestamps: true }
);

// Unique partial index — ensures one notification per (user, notificationKey)
// while still allowing old documents that lack notificationKey to coexist.
notificationSchema.index(
  { user: 1, notificationKey: 1 },
  {
    unique: true,
    partialFilterExpression: { notificationKey: { $type: 'string' } },
    name: 'user_notificationKey_unique',
  }
);

notificationSchema.index({ user: 1, scheduledAt: -1 });
notificationSchema.index({ user: 1, isRead: 1, scheduledAt: -1 });

module.exports = mongoose.model('Notification', notificationSchema);
