export { GateNexaReport } from './GateNexaReport';
export type { GateNexaReportProps } from './GateNexaReport';
export type { ReportData, ProgrammeRow, Candidate, ReportMeta } from './types/report.types';
export { sampleReportData } from './data/sampleReportData';
export { colors, tierColors } from './theme/colors';
export { fontSize, fontFamily, letterSpacing, lineHeight } from './theme/typography';
export { layout, spacing, radius } from './theme/spacing';
export { tierFromPercent, TABLE_LEGEND_DEFINITIONS } from './utils/chanceUtils';
export { formatLakhs, formatPercent, formatRange, orDash } from './utils/formatters';
export { registerFonts } from './fonts/registerFonts';
